# 1d Array
* Create a 1-dimensional NumPy array with elements [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].
* Calculate the sum and average of the array elements.
* Multiply the array by a scalar value of 3.
* Slice the array to select elements from the 3rd to the 7th position.
* Compute the sum and average of the sliced array

In [49]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr_sum = np.sum(arr)
arr_avg = np.average(arr)
arr3 = np.multiply (3, arr)
sliced_arr = arr[2:7]
sliced_sum = np.sum(sliced_arr)
sliced_avg = np.average(sliced_arr)

print(arr)
print(arr_sum)
print(arr_avg)
print (arr3)
print(sliced_arr)
print(sliced_sum)
print(sliced_avg)

[ 1  2  3  4  5  6  7  8  9 10]
55
5.5
[ 3  6  9 12 15 18 21 24 27 30]
[3 4 5 6 7]
25
5.0


# Multi-dimensional array
* Create a 3x3 matrix with the following rows in order: {3,4,5} {6,7,8} {9,1,2}
* Print the element in the second row, third column.
* Print the second row
* Print the second column
* Compute the transpose of the matrix

In [50]:
import numpy as np

mat = np.matrix([[3,4,5],[6,7,8],[9,1,2]])
print(mat[1,2])
print(mat[1,])
print(mat[:,1])
trans = mat.transpose()
print(trans)


8
[[6 7 8]]
[[4]
 [7]
 [1]]
[[3 6 9]
 [4 7 1]
 [5 8 2]]


# Concatenation
* Create two 1-d arrays: [5,1,4,2] and [6,10,11,7]
* Concatenate the two arrays
* Sort the new array from lowest to highest
* Split the result from the previous step into two equal sized arrays

In [51]:
import numpy as np

arr1 = np.array([5,1,4,2])
arr2 = np.array([6,10,11,7])
concat = np.concatenate([arr1,arr2])
print(concat)
sorted_concat = np.sort(concat)
print(sorted_concat)
split_arr = np.split(sorted_concat, 2)
print(split_arr)



[ 5  1  4  2  6 10 11  7]
[ 1  2  4  5  6  7 10 11]
[array([1, 2, 4, 5]), array([ 6,  7, 10, 11])]


# Mathematical functions
* Create an array with values from 0 to 4*pi in increments of pi/2 (pi refers to the mathematical constant  π)
* Compute an array that applies the mathematical sin function to the original array
* Do the same for the following mathematical functions: cos, log, exp
* Compute the mean, median, and standard deviation of each resultant array

In [5]:
import numpy as np
import math

def print_stats(arr, name):
    print(f"{name} array: {arr}")
    i = 0
    while i < len(arr):  #take out undefined elements
        if arr[i] == np.inf or arr[i] == -(np.inf) or arr[i] == np.nan:
            arr = np.delete(arr, i)
            continue
        i+= 1
    mean = np.average(arr)
    median = np.median(arr)
    std = np.std(arr)
    print(f"mean: {mean}")
    print(f"median: {median}")
    print(f"std dev: {std}")
    print("\n")
    
pi_arr = np.array([])
for i in range (0, 9):
    pi_arr = np.append(pi_arr, [i/2*math.pi])
print_stats (pi_arr, "pi")

sin_arr = np.sin(pi_arr)
print_stats (sin_arr, "sin")

cos_arr = np.cos(pi_arr)
print_stats(cos_arr, "cos")

log_arr = np.log(pi_arr)
print_stats(log_arr, "log")

exp_arr = np.exp(pi_arr)
print_stats(exp_arr, "exp")
    

pi array: [ 0.          1.57079633  3.14159265  4.71238898  6.28318531  7.85398163
  9.42477796 10.99557429 12.56637061]
mean: 6.283185307179587
median: 6.283185307179586
std dev: 4.055778675973612


sin array: [ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00
 -2.4492936e-16  1.0000000e+00  3.6739404e-16 -1.0000000e+00
 -4.8985872e-16]
mean: -2.975712385932333e-17
median: 0.0
std dev: 0.6666666666666666


cos array: [ 1.0000000e+00  6.1232340e-17 -1.0000000e+00 -1.8369702e-16
  1.0000000e+00  3.0616170e-16 -1.0000000e+00 -4.2862638e-16
  1.0000000e+00]
mean: 0.11111111111111106
median: 6.123233995736766e-17
std dev: 0.7370277311900889


log array: [      -inf 0.45158271 1.14472989 1.55019499 1.83787707 2.06102062
 2.24334217 2.39749285 2.53102425]
mean: 1.7771580681326111
median: 1.9494488420664502
std dev: 0.6579655683239043


exp array: [1.00000000e+00 4.81047738e+00 2.31406926e+01 1.11317778e+02
 5.35491656e+02 2.57597050e+03 1.23916478e+04 5.96097415e+04
 2.86751313e+05

/var/folders/03/ncpt0f556jn9mwpykfyp_0rr0000gn/T/ipykernel_2847/2514866737.py:31: RuntimeWarning: divide by zero encountered in log
  log_arr = np.log(pi_arr)


# Boolean Indexing and Filtering
* Create a 1-d array with all multiples of 5 from 15 to 80, and also include 12
* Create a boolean array that identifies elements which are greater than 25
* Use that boolean array to filter out elements greater than 25 from the original array.

In [2]:
import numpy as np
arr = np.array([12])
for i in range (3, 17):
    arr = np.append (arr, [i * 5])
print (arr)
bool_arr = ~(arr > 25)
print(bool_arr)
filtered = arr[bool_arr]
print(filtered)

[12 15 20 25 30 35 40 45 50 55 60 65 70 75 80]
[ True  True  True  True False False False False False False False False
 False False False]
[12 15 20 25]
